### ISSUE TITLE
Feature: User can make a journal entry

### ISSUE THREAD

**Issue by Quintin-Russell** [Quintin-Russell/mood-trace#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

Users can make a new journal entry

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

The user can document 5 things that they are grateful for and a free-form journal

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/75178406/126260730-595cc77a-ace8-4722-b78d-b5b6a28f04b2.png)
![image](https://user-images.githubusercontent.com/75178406/126260762-c5507ca2-f920-4d2f-b00c-819094d10ed6.png)
![image](https://user-images.githubusercontent.com/75178406/126260771-09551603-9fcf-45d5-84c5-b3cd86a362ea.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] create home screen
- [x] set up `data.js` w/ `entries` array and `drafts` array
- [x] add `newEntry` constructor function
    - [x] makes object with keys: `title` , `fiveThings` , 'text' , 'response' , 'score', `scoreNum`
    - [x] `title` = the days date and hour 
- [x] set up `main.js` w/ `eventListeners` on all buttons on home screen
- [x] create container `div` w/ class `container`
    - [x] `display: flex` ; `flex-direction: column` ; `align-items: center` ; `justify-content: center` 
- [x] create 2 more sub `div`s w/ classes `grateful` and `new-journal`; `display: hidden`
- [x] `grateful`
     - [x] make header w/ `ul` w/ 2 `li`s : 1 `a` that links to the home page,  one `p` element 
     - [x] add title bar
         - [x] `div` w/ class `row` > `img` and `div`
         - [x] 2nd `div` w/ `section` an `h2` and `p`; h2 = "New Journal" and p = "Date: _____" ()
         - [x] set 2nd `div` background to `C1AC95` w/ transparency 20%
     - [x] add `div` w/ class `grateful-content`: `flex-direction: column` , `justify-content: center` , `align- 
            items: center`
         - [x] add `form` element
         - [x] add `h2` = "What are 5 things that you are grateful for?" 
         - [x] add 5 `<textarea>` elements
         - [x] add button `<footer>` w/ class `row` and `justify-content: space between`
             - [x] button color = `C9E4C5`
             - [x] 1 button = "Save as Draft"; 1 button = "Continue"
             - [x] add `eventListener` to `Continue button`: changes `display` property from `hidden` to 
                   `flex`  on `new-journal-cont` and vice versa for `grateful` ``div`

-[ ] `new-journal` 
    - [ ] add header
    - [ ] add title bar
    - [ ] add `div` w/ `background-color: C1AC95` and `transparency: 20%`
    - [ ] add `<textarea>`  element w/ `placeholder = __string__`
    - [ ] add 2 buttons: "Save as Draft" and "Done!"
- [ ]add `eventListener` to `Done! button` that creates journal object
    -[ ] title = current date and hour  
    -[ ] event listener adds 5 things to an array
    -[ ] adds array to journal object 
    -[ ]  adds `new journal cont` text content to journal object
    -[ ] adds journal entry to `entries` array
    -[ ] submits `journal.text` to api
    -[ ] recieves response and adds response obj to journal entry
-[ ] Done modal
    -[ ] `div.overlay+hidden>div.textbox>section>h2+p `
        -[ ] `.textbox` = `display: inherit` , `flex-direction: column` , `align-items: center`
        -[ ] `.hidden` = 'display: hidden' ; `.flex` = `display: flex`
        -[ ] `.overlay` = `background: rgba(0, 0, 0, 0.61)`; `position: absolute`;  `top: 0`;  `bottom: 0`;  `left: 0`;  `right: 0`;  `display: 
               inherit`;  `justify-content: center`;  `align-items: center`
    -[ ] display `journal.score` inside a `h2`
    -[ ] based on number score, motivational passage displayed
    -[ ] create close 'X'  

- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
