### ISSUE TITLE
Feature: User can see their journal entry plotted on a ‘mood graph’ 

### ISSUE THREAD

**Issue by Quintin-Russell** [Quintin-Russell/mood-trace#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see their journal entry plotted on a ‘mood graph’

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users will be able to click a button on the home screen and see their past MoodScores plotted on a line graph 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/75178406/126424526-bc0660af-2784-4429-bbfa-e5e90661c3b3.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] add `eventListener` to "View Your MoodGraph" button that changes `div.moodgraph` 's `display` property to `flex`
    - [x] make function that compiles `entry.scoreNum` and adds to premade request to Chart API 
- [x] HTML: `div.container>div>canvas#myChart>button`
- [x] add `<script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0"></script>`
- [x] add header
- [x] add text to the button: "Return to Home Screen"

- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
