### ISSUE TITLE
Feature: User can save an entry as a draft

### ISSUE THREAD

**Issue by Quintin-Russell** [Quintin-Russell/mood-trace#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can save an entry as a draft

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users will be able to press a `Save as Draft` button to save a journal entry as a draft for editing later

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/75178406/126427137-78680132-8958-4a61-a2c0-8aa9dec8522b.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.
-[ ] add `eventListener` to `Save as Draft` button that:
    -[ ] creates a journal object and adds available information, but does not submit request to API
    -[ ] saves object to `drafts` array

- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.

- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
