### ISSUE TITLE
Feature: User can view and edit their list of drafts

### ISSUE THREAD

**Issue by Quintin-Russell** [Quintin-Russell/mood-trace#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view and edit their list of drafts

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to click `Drafts` button to access a list of `draft` icons. Users can then click a `draft` icon to edit the entry

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![image](https://user-images.githubusercontent.com/75178406/126424755-01bea86c-323c-4bf3-be47-a4034fed952a.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] add `eventListener` to `Drafts` button home screen
    - [ ] make function that makes DOM element for each item in the `drafts` array
    - [ ] adds each DOM element o a `$draft` array
- [ ] add `eventListener` to container `div` that determines `event.target` 
    - [ ] if `(entry.fiveThings.length < 5)`  : `grateful` `div` 's `display` property = `flex` 
        - [ ] fills `<textarea>` elements with available text
    - [ ] `else` :   
        - [ ]`new-journal` `div` 's `display` property = `flex` 
        - [ ] fills `<textarea>` elements with available text 

- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [ ] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [ ] Remove all console logs.
  - [ ] Remove all commented out code.
  - [ ] Remove all CSS properties that have no effect.
  - [ ] Check all code for proper formatting and indentation.
  - [ ] Confirm that there are no errors in the console while using the application.
  - [ ] Confirm that all previous functionality still works without errors.
  - [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [ ] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
